/* ============================================================
   Portfolio content. Edit this file to update the website.
   All image paths are relative to the portfolio/ root folder.
   ============================================================ */

const PERSONAL = {
  name: "Reza Fadli Harris",
  firstName: "Reza",
  roles: ["iOS Engineer", "Mobile Developer", "Full-Stack Developer", "Problem Solver", "Team Player"],
  summary:
    "I’m a tech enthusiast with over <strong>5 years of experience in software engineering</strong> including <strong>Mobile & Web development</strong>, with experience working as a <strong>Project Manager</strong> and <strong>Designer</strong>. Passionate about solving social-based problems, my ultimate goal is to create high-quality software that provides effective solutions and makes a meaningful impact.",
  email: "rezafh19@gmail.com",
  linkedin: "https://www.linkedin.com/in/rezaharris/",
  github: "https://github.com/RezaNum1",
  instagram: "https://www.instagram.com/rezafhar",
  instagramHandle: "@rezafhar",
};

const SKILLS = [
  {
    icon: "📱",
    title: "iOS Engineering",
    note: "My core expertise: building polished, large-scale iOS & iPadOS apps.",
    items: ["Swift", "SwiftUI", "UIKit", "Combine", "TCA", "CoreData", "CloudKit", "StoreKit", "AVFoundation", "HealthKit", "MapKit", "Vision / ML Kit", "PSPDFKit", "Kotlin Multiplatform", "Lottie"],
    hl: ["Swift", "SwiftUI", "UIKit", "TCA"],
  },
  {
    icon: "🌐",
    title: "Web & Cross-Platform",
    note: "Full-stack product building across web and mobile.",
    items: ["Flutter", "Next.js", "Vue.js", "Nest.js", "Express.js", "Symfony", "GraphQL", "Apollo", "Prisma ORM", "Twig"],
    hl: ["Flutter", "Next.js", "GraphQL"],
  },
  {
    icon: "🗄️",
    title: "Backend & Cloud",
    note: "Databases, storage and infrastructure that scale.",
    items: ["PostgreSQL", "Firebase", "Amazon S3", "AWS RDS", "Red Hat Enterprise Linux", "Tesseract OCR"],
    hl: ["PostgreSQL", "Firebase"],
  },
  {
    icon: "🧭",
    title: "Architecture & Practices",
    note: "Writing code that stays maintainable as teams and apps grow.",
    items: ["MVVM + Repository", "The Composable Architecture", "VIP (Clean Architecture)", "MVC", "Atomic / Reusable Components", "Unit & UI Testing", "SwiftLint", "MoEngage · Insider · Mixpanel", "Deep Link / Universal Link"],
    hl: ["The Composable Architecture", "VIP (Clean Architecture)"],
  },
];

const STATS = [
  { value: 5, suffix: "+", label: "Years of Experience" },
  { value: 9, suffix: "", label: "Projects Showcased" },
  { value: 34, suffix: "K+", label: "Active Users (Kompas.id)" },
  { value: 4.9, suffix: "★", label: "App Store Rating", decimals: 1 },
];

const MARQUEE = ["SwiftUI", "UIKit", "The Composable Architecture", "Combine", "Kotlin Multiplatform", "Flutter", "Next.js", "Vue.js", "Nest.js", "GraphQL", "Firebase", "PostgreSQL", "Amazon S3", "CoreData", "CloudKit", "StoreKit", "HealthKit", "Vision"];

const PROJECTS = [
  {
    slug: "kompas-id",
    name: "Kompas.id",
    featured: true,
    category: "News & Magazine",
    platforms: ["iOS", "iPadOS"],
    type: "Professional Work",
    color: "#3b82f6",
    tagline: "One of the largest & most trusted news portals in Indonesia. Premium journalism by Kompas Gramedia, trusted since 1965.",
    cover: "assets/img/kompas/kompasid_1.png",
    coverPos: "center 30%",
    featStats: [
      { b: "34K+", s: "Active users" },
      { b: "4.9 / 5.0★", s: "App Store rating" },
      { b: "Top 3", s: "News chart (Free Apps)" },
    ],
    about: [
      "Kompas.id is a news platform created by Kompas Gramedia Nusantara, one of the biggest & oldest news companies in Indonesia, providing premium news with a special experience for newspaper readers. It offers subscription plans and is the concrete step of digitalizing their paper-based news product. There are over 34K active users across all platforms, an App Store rating persisting at 4.9/5.0★, and a spot in the top 3 charts for Magazines & Newspapers (Free Apps).",
      "Kompas.id is a multi-platform application supported on Website, Android & iOS. On the Apple platform it supports both iOS & iPadOS with different layouts for each to give users the best experience. The app serves multiple user types with different access levels, so customer-oriented thinking is the most important value in developing this product.",
    ],
    techStack: ["SwiftUI", "UIKit", "Kotlin Multiplatform", "Firebase", "Kingfisher", "PSPDFKit", "Combine", "CoreData", "CoreLocation", "AVKit", "AVFoundation", "Audio Streaming", "Media Player", "CryptoKit", "SVGKit", "WebKit", "StoreKit"],
    architecture: "MVVM + Repository & The Composable Architecture (TCA)",
    contributions: [
      "Maintaining and increasing code quality periodically through the latest frameworks & technology from Apple.",
      "Built the Text-to-Speech premium feature: smooth audio with playback, next/previous, and speed-up controls, background playing, lock-screen control, and AirPods/earphone support.",
      "Built the eBook section leveraging PSPDFKit to present original PDF content from cloud storage, accessible both online and offline.",
      "Implemented custom Interactor functionalities to reduce Refresh & Access-token API calls, cutting server load without third-party dependencies.",
      "Revamped the whole Combine-based flow into async/await across ClientAPI, Service, Repository, ViewModel and Views, simplifying business logic and reducing code redundancy.",
      "Revamped the view code structure into reusable components and implemented atomic code design.",
      "Implemented analytics & campaign tools (MoEngage, Insider and Mixpanel) to track user behavior for marketing & product decisions.",
      "Enhanced navigation & navigation-bar code to work smoothly from iOS 14 to iOS 18.",
      "Managed View & business-logic code supporting two platforms: iOS & iPadOS.",
      "Implemented Deep Link & Universal Link for marketing/campaign purposes.",
      "Built a dynamic content area to handle special events/campaigns, quickly manageable from the web.",
      "Enhanced complex authentication flows so they're easier to understand, maintain, and free of repetitive bugs.",
      "Managed the subscription code bloc through SwiftyStoreKit, later migrated to StoreKit.",
      "Enforced general developer rules across the codebase leveraging SwiftLint.",
      "Migrating the app architecture to The Composable Architecture: modular, unit-testable and UI-testable.",
    ],
    impact: [
      "App crash-free rate persisted above 96%",
      "Codebase easy to maintain & understand, even for new team members",
      "4.9 / 5.0★ App Store rating and top 3 in Magazines & Newspapers charts",
    ],
    galleryStyle: "phones",
    gallery: Array.from({ length: 14 }, (_, i) => ({ src: `assets/img/kompas/kompasid_${i + 1}.png`, tall: true })),
  },
  {
    slug: "donor-plus",
    name: "Donor+",
    category: "Health",
    platforms: ["iOS", "iPadOS", "Website"],
    type: "Team Project",
    color: "#e2604f",
    tagline: "Easing manual registration & preliminary screening for convalescent plasma donors, connecting donors and the Indonesian Red Cross (PMI) during Covid-19.",
    cover: "assets/img/donorplus/donorplus_1.png",
    about: [
      "Donor+ is an app that eases the manual registration and preliminary screening process for potential convalescent plasma donors, as well as status information for each stage of the process.",
      "During the Covid-19 wave in Indonesia, convalescent plasma was one of the available therapies, but there was no dedicated platform for donors. Registration wasn't easy and administration took days, while PMI (Indonesian Red Cross) struggled to sort the data. Donor+ was built to make it easy for both donors and PMI.",
    ],
    techStack: ["SwiftUI", "Firebase", "Lottie", "GraphQL", "Next.js", "Prisma ORM", "Amazon S3", "PostgreSQL", "Apollo", "Express.js", "CoreData", "HealthKit", "AVFoundation", "SwiftLint"],
    architecture: "MVVM (Mobile) & MVC (Web)",
    sections: [
      {
        title: "iOS App",
        bullets: ["Integration with Health App", "Donor Qualification Test", "Register to nearest UDD PMI", "Online Registration Form", "QR Code for the queueing process", "Track each donor process"],
        text: "Built with SwiftUI as the main framework, interfacing with UIKit for MapKit views, Sign in with Apple, and EventKit for iCal reminders. Apollo iOS generates models from GraphQL queries; push notifications are handled via Firebase Cloud Messaging to deliver status changes pushed from the back office.",
      },
      {
        title: "Web Back-Office (PMI)",
        bullets: ["Identity Access Management for PMI", "Manage UDD PMI admins", "Monitor donor process & update active donor status", "See donor data", "Manage schedules and time slots"],
        text: "Built with Next.js for its pre-rendering and data-fetching features, essential since the back office displays a lot of information. It communicates through Apollo GraphQL, with Formik for quick form submission & validation.",
      },
      {
        title: "Backend & Database",
        text: "GraphQL as the API query language with Apollo Server on Express.js, where one call can insert, update or delete across several tables. PostgreSQL hosted on AWS RDS as the primary database, and AWS S3 for storing images uploaded from the iOS app.",
      },
    ],
    galleryStyle: "grid",
    gallery: [
      { src: "assets/img/donorplus/donorplus_1.png" },
      { src: "assets/img/donorplus/donorplus_techstack.webp" },
    ],
  },
  {
    slug: "cekidot",
    name: "Cekidot",
    category: "Food & Drink",
    platforms: ["iOS"],
    type: "Team Project",
    color: "#84a832",
    tagline: "An iOS app that helps people find food that suits their dietary habits & allergen preferences at their next grocery stop.",
    cover: "assets/img/cekidot/cekidot_app_profile.webp",
    coverPos: "top",
    about: [
      "Cekidot helps people find food that suits their dietary habits and allergen preferences. By quickly digesting the information inside the ingredients & food-composition section, users can identify healthier options and avoid potential allergens.",
      "Cekidot features a Traffic Light System (TLS) that makes nutrition facts easy to understand by instantly showing whether the amount of macronutrients, salt, and sugar is right.",
      "The idea came from a teammate with food allergies who had to be extra careful when grocery shopping. After interviews with potential users, it turned out many people face the same struggle: composition text is hard and slow to digest. So we decided to tackle the problem our own way.",
    ],
    techStack: ["SwiftUI", "Firebase", "Lottie", "CoreData", "CloudKit"],
    architecture: "VIP: View, Interactor & Presenter (Clean Architecture)",
    sections: [
      {
        title: "Why VIP Architecture?",
        text: "VIP consists of six parts (View, Interactor, Presenter, Model, Worker, and Router) with a unidirectional flow. The Model, Worker & Router parts are decoupled from the View and business logic, so they can be shared anywhere. This answered our concern about switching data sources between CloudKit modes.",
      },
      {
        title: "Module Template Generator",
        text: "We built a generator that scaffolds a full VIP module automatically: six pre-set files with customizable prefixes, increasing time efficiency every time a new feature is created.",
      },
      {
        title: "Reusable Components & CloudKit",
        text: "Every developer thinks reusable-first before building a feature. One change in a component applies everywhere it's used, which makes design iterations easy to absorb. CoreData + CloudKit act as the main database with automatic data sync across the user's devices, no custom backend needed.",
      },
    ],
    galleryStyle: "grid",
    gallery: [
      { src: "assets/img/cekidot/cekidot_app_profile.webp", tall: true },
      { src: "assets/img/cekidot/cekidot_clean_arch.webp" },
      { src: "assets/img/cekidot/cekidot_template.webp" },
      { src: "assets/img/cekidot/cekidot_components.webp" },
      { src: "assets/img/cekidot/cekidot_database.webp" },
      { src: "assets/img/cekidot/cekidot_teammates.webp" },
    ],
  },
  {
    slug: "dhelp",
    name: "D-Help!",
    category: "Health · Utilities",
    platforms: ["iOS"],
    type: "Team Project",
    color: "#1d998e",
    tagline: "Helping people with type-2 diabetes control their blood sugar every day by monitoring their daily food consumption.",
    cover: "assets/img/dhelp/dhelp_1.png",
    about: [
      "An iOS application helping people with type-2 diabetes control their blood sugar daily by monitoring their food consumption.",
      "Many people diagnosed with type-2 diabetes find it hard to control daily consumption. High-sugar food can spike blood sugar quickly, so they must remember everything they've eaten and be careful about consuming it again. D-Help! helps them control & monitor daily consumption, and search any food including its sugar micro-ingredient info.",
    ],
    techStack: ["UIKit", "Lottie", "CoreData", "Core Animation", "HealthKit", "SwiftLint"],
    architecture: "MVC",
    galleryStyle: "grid",
    gallery: [{ src: "assets/img/dhelp/dhelp_1.png" }],
  },
  {
    slug: "see-diagram",
    name: "See Diagram",
    category: "Utilities · Accessibility",
    platforms: ["iOS"],
    type: "Team Project",
    color: "#f2766b",
    tagline: "An iOS app that helps blind people understand flowcharts through vision with embedded machine learning.",
    cover: "assets/img/seediagram/seediagram_1.png",
    about: [
      "See Diagram is an iOS app that helps blind people understand a flowchart through vision with embedded machine learning.",
      "When our team visited a blind community, we found that some of them were interested in learning programming, but first they needed to understand flowcharts that visualize business processes. Starting from that problem, we collected information about what they desire to learn and implemented the solution through this application.",
    ],
    techStack: ["UIKit", "Lottie", "CoreData", "ML Kit", "Vision", "AVFoundation", "SwiftLint"],
    architecture: "MVC",
    galleryStyle: "grid",
    gallery: [{ src: "assets/img/seediagram/seediagram_1.png" }],
  },
  {
    slug: "attack-on-phobia",
    name: "Attack On Phobia",
    category: "Game",
    platforms: ["iOS"],
    type: "Personal Project",
    color: "#e8574f",
    tagline: "An iOS game with a storyline & interactive scenes: defeating a phobia monster with a sense of courage to change.",
    cover: "assets/img/aop/aop_1.png",
    about: [
      "An iOS game with a storyline continued by an interactive monster-defeating scene, inspired by the game Bishi Bashi, conveying how heavy it felt to overcome fear with a sense of courage to change.",
      "I created this game inspired by a phobia I've had since childhood. Through this game, I visualize how to fight the feeling of fear... of a fruit. 🍓",
    ],
    techStack: ["UIKit", "Core Animation", "AVFoundation", "SwiftLint"],
    architecture: "MVC",
    galleryStyle: "grid",
    gallery: [
      { src: "assets/img/aop/aop_1.png" },
      { src: "assets/img/aop/aop_2.png" },
      { src: "assets/img/aop/aop_3.png" },
    ],
  },
  {
    slug: "akantan",
    name: "Akantan Warga",
    category: "Utilities · Govt Service",
    platforms: ["iOS", "Android", "Website"],
    type: "Thesis Project",
    color: "#f5a623",
    tagline: "Simplifying village-level certificate submission, with OCR that reads KTP & KK so residents never re-fill the same data twice.",
    cover: "assets/img/akantan/akantan_1.png",
    coverPos: "top",
    about: [
      "Akantan is a mobile & web application that aims to simplify the process of submitting certificates whose services are at the village (kelurahan) level, fully online from submission to approval tracking.",
      "The app is equipped with OCR (Tesseract) to scan & recognize KTP & KK data easily, so residents don't need to repeatedly fill in the same data for every certificate. It also uses the Levenshtein-distance algorithm to correct scanned text, plus features like electronic signature, automatic letter distribution, and online document checking.",
    ],
    techStack: ["Flutter", "Symfony 4", "Twig", "Amazon S3", "PostgreSQL", "Tesseract OCR", "Firebase"],
    architecture: "MVC",
    galleryStyle: "grid",
    gallery: [
      { src: "assets/img/akantan/akantan_1.png", tall: true },
      { src: "assets/img/akantan/akantan_2.png" },
      { src: "assets/img/akantan/akantan_3.png" },
      { src: "assets/img/akantan/akantan_4.png", tall: true },
      { src: "assets/img/akantan/akantan_5.png" },
      { src: "assets/img/akantan/akantan_6.png" },
    ],
  },
  {
    slug: "aam",
    name: "Activity Approval Management",
    category: "Enterprise · Utilities",
    platforms: ["Website"],
    type: "Professional Work · Danone",
    color: "#2b8fd8",
    tagline: "A website for Danone to manage CSR budgets: budgeting, approval workflow, and monitoring across all branches.",
    cover: "assets/img/aam/aam_1.png",
    about: [
      "A full-stack website built for Danone to manage their CSR budget across all branches.",
    ],
    features: ["Budget Control (budgeting & controlling for all branches)", "Activity Request Workflow", "Report Activity", "Report Budget (Budget Monitoring)", "User Management", "Master Data"],
    techStack: ["Nest.js", "Vue.js", "Amazon S3", "Red Hat Enterprise Linux", "PostgreSQL"],
    architecture: "MVC",
    galleryStyle: "grid",
    gallery: [{ src: "assets/img/aam/aam_1.png" }],
  },
  {
    slug: "idx-attendance",
    name: "IDX QR Attendance",
    category: "Utilities · Enterprise",
    platforms: ["Website"],
    type: "Professional Work · Indonesia Stock Exchange",
    color: "#8b5cf6",
    tagline: "QR-code based attendance system for employees at the Indonesia Stock Exchange office. Scan once, recorded automatically.",
    cover: "assets/img/idx/idx_cover.svg",
    about: [
      "QRCode Attendance IDX is a website-based application created for employee attendance needs at the Indonesia Stock Exchange office. Every employee who wants to record attendance simply scans their QR code, and attendance data is then created automatically by the system.",
      "The system also has a QR-generation engine for onboarding new employees.",
    ],
    techStack: ["Symfony 4", "Twig", "Amazon S3", "PostgreSQL"],
    architecture: "MVC",
    galleryStyle: "none",
    gallery: [],
  },
];
